[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
dummy = "BMSDHjY74HZAknfMBvNF6fjVStM1pPe5hiVhQqDwSFfw"
flashloan = "4j61cgEWFvVyMhdLJz9wLpuEnny8UBcva5wDNqYbWdn1"

[provider]
cluster = "devnet"
wallet = "keys/ANDYPEbY29yk7y93V4DJTxnEqHe9AnSHtMKyXaNd8Dgi.json"

[scripts]
test = "cargo test"

[hooks]
