[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
flashloan = "FsLos6rnXoPrhjTrW4qfiypcy47WrJRibZXBJGMDy8iD"

[provider]
cluster = "devnet"
wallet = "keys/ANDYPEbY29yk7y93V4DJTxnEqHe9AnSHtMKyXaNd8Dgi.json"

[scripts]
test = "cargo test"

[hooks]
