[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flashloan = "DtzrtfA92R7zvHxSpPhg5mCiVDBgwGfCkuPKcD23Sio"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
